// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl4QTB6NvhQpLux4zPiSsd2fLhL0WvzGs',
    appId: '1:640044814754:web:dadee49f9b5e8f8a7e22fb',
    messagingSenderId: '640044814754',
    projectId: 'taller-firebase-universi-78ccf',
    authDomain: 'taller-firebase-universi-78ccf.firebaseapp.com',
    storageBucket: 'taller-firebase-universi-78ccf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtp26CIY3LbhTcafQXNPLIZ3a3hJ6Sg-w',
    appId: '1:640044814754:android:cb8a5540704c07e87e22fb',
    messagingSenderId: '640044814754',
    projectId: 'taller-firebase-universi-78ccf',
    storageBucket: 'taller-firebase-universi-78ccf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoh6nihcSO5QnkD92lrCWkpdjzQ2HsUvY',
    appId: '1:640044814754:ios:75a50e2feb037ec37e22fb',
    messagingSenderId: '640044814754',
    projectId: 'taller-firebase-universi-78ccf',
    storageBucket: 'taller-firebase-universi-78ccf.firebasestorage.app',
    iosBundleId: 'com.juandiiego.tallerFirebaseUniversidades',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoh6nihcSO5QnkD92lrCWkpdjzQ2HsUvY',
    appId: '1:640044814754:ios:75a50e2feb037ec37e22fb',
    messagingSenderId: '640044814754',
    projectId: 'taller-firebase-universi-78ccf',
    storageBucket: 'taller-firebase-universi-78ccf.firebasestorage.app',
    iosBundleId: 'com.juandiiego.tallerFirebaseUniversidades',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl4QTB6NvhQpLux4zPiSsd2fLhL0WvzGs',
    appId: '1:640044814754:web:92d938e3637902927e22fb',
    messagingSenderId: '640044814754',
    projectId: 'taller-firebase-universi-78ccf',
    authDomain: 'taller-firebase-universi-78ccf.firebaseapp.com',
    storageBucket: 'taller-firebase-universi-78ccf.firebasestorage.app',
  );
}
